---
title: "Teaching"
---

I am a visiting thesis supervisor for students on the data science track of the mathematics programme at the [Budapest University of Technology and Economics](https://www.bme.hu/?language=en). If you're intending to write your thesis on a topic related to my research interests, you're probably in the right place.


# Procedural aspects

Each year, the department publishes a list of thesis topics. You can find the list for the current academic year. If you're interested in one of the topics, you should contact the supervisor listed for that topic. If you're interested in one of my topics, you should contact me.

As I am not full-time faculty, you will need to find an internal supervisor as well. The department has been very supportive of my students in the past, so this should not be a problem.

While not a strict requirement, I would be very grateful if students aspiring to work with me could please make themselves known a few months before start of term. This will allow me to plan my time better, and to make sure that I can give you the attention you deserve.


# Expectations

You will generally be expected to create quality research-backed work based on the topic you choose. This means that you will need to read and understand the relevant literature, and you will need to be able to implement the algorithms you study. You will also need to be able to evaluate your work, and to compare it to existing methods. In short, you will need:

* a good lit review,
* a well-identified research gap,
* a decent treatment of the latter, and
* all of this done in a sound, scientific and reproducible manner.

The expectation is that you will do the bulk of the work over a period of 6 months, and that you will be able to write up your results in a thesis of 40-60 pages. You will also be expected to present your work at a thesis defence.

Students may, at present, write their theses in English or in Hungarian. I have no preference for either, but I do expect that you will be able to write _well_ in whichever language you choose. The _lingua franca_ of data science, at the moment, is English, so if you're planning to work in the field, you should probably be able to write in English. If you're looking for employment abroad, a thesis in English will carry you a long way.


# Topics

Past topics have included agent-based models of infectious diseases, disproportionality analyses of vaccination, computer vision on Synthetic Aperature Radar images for forest cover detection, and much more.

Every year I offer four topics for no more than two places. Of these, three tend to come from the biomedical domain, and at least one has some computer vision aspect. The topics are usually related to my research interests, and are usually related to my key research interests.


# Technology

As far as I'm concerned, you can write your thesis using whatever widely used software you prefer. Obviously, writing your models in an esoteric language like Befunge or Malbolge will not endear you to the faculty, but within reason, you're fine. Python by far is the most popular choice among my students.

Remember that whatever topic you pick, you're responsible for doing the work. This means that you will have to figure out how to cover costs of computation if these are non-trivial. The faculty may be able to help, as could I, but you should not expect this. This is particularly relevant for LLM related topics or where there are data access costs.