---
title: Papers
---

# 2023

::: {#refs .references .csl-bib-body .hanging-indent line-spacing="2"}

::: {#ref-mogere2023juvenile .csl-entry}
Mogere, E., Mwaura, E., Waithaka, M., Mutua, V., Mugao, M., **von Csefalvay,
C.**, & Mukamati, D. (2023). Juvenile polyposis syndrome: A case
report. *Clinical Case Reports*, *11*(1), e6798.
:::

:::



# 2022

::: {#refs .references .csl-bib-body .hanging-indent line-spacing="2"}

::: {#ref-bundi2022unusual .csl-entry}
Bundi, B. N., Mutua, V., Cheruiyot, I., Munguti, J., **von Csefalvay, C.**,
Nurani, K. M., & Ogeng'o, J. (2022). The unusual high origin radial
artery in a black Kenyan population: A cadaveric study. *Ethiopian
Journal of Health Sciences*, *32*(2).
:::

::: {#ref-munguti2022tuberculous .csl-entry}
Munguti, J., Mutua, V., Cheruiyot, I., **von Csefalvay, C.**, Opare-Addo,
P., Kiko, N., & Wanjiru, R. (2022). Tuberculous polyserositis in endemic
areas with an emphasis on empiric therapy: A case report. *Medicine:
Case Reports and Study Protocols*, *3*(4), e0221.
:::

::: {#ref-mutua2022tocilizumab .csl-entry}
Mutua, V., Henry, B. M., **von Csefalvay, C.**, Cheruiyot, I., Vikse, J.,
Lippi, G., Bundi, B., & Mong'are, N. (2022). Tocilizumab in addition to
standard of care in the management of COVID-19: A meta-analysis of RCTs.
*Acta Bio Medica: Atenei Parmensis*, *93*(1).
:::

:::


# 2021

::: {#refs .references .csl-bib-body .hanging-indent line-spacing="2"}

::: {#ref-von2021case .csl-entry}
**von Csefalvay, C.** (2021). A case-control study of autoimmune AEFIs
following COVID-19 vaccination reported to VAERS. *medRxiv*, 2021--2007.
:::

::: {#ref-von2021anaphylactic .csl-entry}
**von Csefalvay, C.** (2021). Anaphylactic events in mRNA vaccines: A
reporting case-control study. *medRxiv*, 2021--2007.
:::

::: {#ref-von2021early .csl-entry}
**von Csefalvay, C.** (2021). Early evidence for the safety of certain
COVID-19 vaccines using empirical bayesian modeling from VAERS.
*medRxiv*, 2021--2006.
:::

::: {#ref-csefalvay2021vaers .csl-entry}
**von Csefalvay, C.** (2021). VAERS data reveals no increased risk of
neuroautoimmune adverse events from COVID-19 vaccines. *medRxiv*,
2021--2006.
:::

::: {#ref-mpekethu2021knowledge .csl-entry}
Mpekethu, N. M., Mongare, N. B., Mutua, V., Wangari, M.-C., **von Csefalvay,
C.**, & Ojuka, D. (2021). Knowledge and attitudes of undergraduate
medical students in Kenya towards solid organ donation and
transplantation: Are Africa's future clinicians prepared? *African
Journal of Nephrology*, *24*(1), 89--94.
:::


::: {#ref-mutua2021sudden .csl-entry}
Mutua, V., Mong'are, N., Bundi, B., **von Csefalvay, C.**, Oriko, D., &
Kitunguu, P. (2021). Sudden bilateral lower limb paralysis with dural
ectasia in neurofibromatosis type 1: A case report. *Medicine: Case
Reports and Study Protocols*, *2*(9), e0165.
:::

:::

# 2020

::: {#refs .references .csl-bib-body .hanging-indent line-spacing="2"}

::: {#ref-von2020statistical .csl-entry}
**von Csefalvay, C.** (2020). Statistical dynamics of social distancing in
SARS-CoV-2 as a differential game. *arXiv Preprint arXiv:2007.13734*.
:::

::: {#ref-von2020vector .csl-entry}
**von Csefalvay, C.** (2020). Vector quantisation and partitioning of
COVID-19 temporal dynamics in the united states. *arXiv Preprint
arXiv:2008.00559*.
:::

::: {#ref-vonpaws .csl-entry}
**von Csefalvay, C.**, & Foldi, T. (2020). *PAWS: Towards a globally
integrated outbreak surveillance system for public health*.
:::

::: {#ref-foldi2020jampi .csl-entry}
Foldi, T., **von Csefalvay, C.** & Perez, N. A. (2020). JAMPI: Efficient
matrix multiplication in spark using barrier execution mode. *Big Data
and Cognitive Computing*, *4*(4), 32.
:::

:::

# 2019

::: {#refs .references .csl-bib-body .hanging-indent line-spacing="2"}

::: {#ref-von2019novel .csl-entry}
**von Csefalvay, C.** (2019). Novel quantitative indicators of digital
ophthalmoscopy image quality. *arXiv Preprint arXiv:1903.02695*.
:::

:::

# 2015

::: {#refs .references .csl-bib-body .hanging-indent line-spacing="2"}

::: {#ref-von2015ecological .csl-entry}
**von Csefalvay, C.** (2015). Ecological metrics of diversity in
understanding social media. *arXiv Preprint arXiv:1501.07621*.
:::

:::

# 2009

::: {#refs .references .csl-bib-body .hanging-indent line-spacing="2"}

::: {#ref-von2009good .csl-entry}
**von Csefalvay, C.** (2009). On good intentions and poor
outcomes: A critical retrospective on _Chester v Afshar_. *UC Dublin L.
Rev.*, *9*, 46.
:::

:::

# 2006

::: {#refs .references .csl-bib-body .hanging-indent line-spacing="2"}

::: {#ref-doorn2006international .csl-entry}
Doorn, N., Vincent, N. A., & Fahlquist, J. N. (eds.) (2006). International
conference on moral responsibility: neuroscience. *Economics and
Philosophy*, *22*, 409--427.
:::

:::